export const categories = [
  "All components",
  "Actions",
  "Inputs",
  "Data display",
  "Feedback",
  "Navigation",
  "Overlays",
] as const;
export type Category = (typeof categories)[number];
export type CatalogItem = {
  name: string;
  title: string;
  category: Category;
  description: string;
  note: string;
};
const rows: [string, string, Category, string, string][] = [
  [
    "data-table",
    "Data table",
    "Data display",
    "Useful data, ready to work with.",
    "Supply rows, typed columns and stable getRowId. Includes client-side filtering, sorting, page selection and pagination. Intended for modest datasets; no virtualization or server queries.",
  ],
  [
    "command",
    "Command",
    "Actions",
    "Find an action without hunting.",
    "Inline command search with arrow keys and Enter. Provide stable item ids and onSelect; compose inside Dialog for a command palette.",
  ],
  [
    "input-group",
    "Input group",
    "Inputs",
    "A field with helpful context.",
    "Compose Input with InputGroupAddon for prefixes, units or actions. Label the input itself; decorative addons may be aria-hidden.",
  ],
  [
    "chip",
    "Chip",
    "Data display",
    "A small, removable detail.",
    "Use onRemove for removable tags and give each remove button a specific removeLabel. Use Badge for static status and ToggleGroup for selection.",
  ],
  [
    "toggle-group",
    "Toggle group",
    "Inputs",
    "A few choices, kept together.",
    "Supply an array of strings with defaultValue or value/onValueChange. Single or multiple mode; arrow keys move focus, Space toggles. Add aria-label.",
  ],
  [
    "steps",
    "Steps",
    "Navigation",
    "Know where you are in a process.",
    "Presentational ordered progress with a zero-based current index. The current step has aria-current. Your application controls validation and navigation.",
  ],
  [
    "timeline",
    "Timeline",
    "Data display",
    "A clear sequence of events.",
    "Compose TimelineItem with a machine-readable dateTime, visible timeLabel and title. Items remain a semantic ordered list.",
  ],
  [
    "copyable-value",
    "Copyable value",
    "Actions",
    "Copy the detail that matters.",
    "Copies the supplied string through the Clipboard API. Announces success or a manual-copy fallback; clipboard access requires a secure context.",
  ],
  [
    "time-picker",
    "Time picker",
    "Inputs",
    "Give a moment its time.",
    "Native time input with name, required, min, max and step. Values use HH:mm or HH:mm:ss; visible format follows the browser locale. No timezone conversion.",
  ],
  [
    "color-picker",
    "Color picker",
    "Inputs",
    "Choose a single accent.",
    "Native color input with value/onChange or defaultValue. Supports opaque sRGB hex colors; label it explicitly. No alpha or palette editor.",
  ],
  [
    "attachment",
    "Attachment",
    "Inputs",
    "Choose files, check the details.",
    "Local file selection with type and size checks, removal and onValueChange(File[]). Default limit 10 MB per file. No upload transport; validate files again on your server.",
  ],
  [
    "action-bar",
    "Action bar",
    "Actions",
    "Actions for the current selection.",
    "Shown when selectedCount is positive. Supply action buttons and onClear. A labeled region groups actions without imposing toolbar keyboard behavior.",
  ],
  [
    "combobox",
    "Combobox",
    "Inputs",
    "Find a choice as you type.",
    "Supply items and render options with ComboboxList. Coal filters and manages keyboard focus. Add ComboboxEmpty for no results.",
  ],
  [
    "calendar",
    "Calendar",
    "Inputs",
    "A considered view of your days.",
    "Written for Coal. Supports single, multiple and range modes, disabled dates, locale and keyboard navigation.",
  ],
  [
    "date-picker",
    "Date picker",
    "Inputs",
    "Give your next idea a date.",
    "Controlled: supply value and onValueChange. Selection closes the popover. Set label for the field purpose.",
  ],
  [
    "native-select",
    "Native select",
    "Inputs",
    "A simple choice with native behavior.",
    "Uses the operating system picker. Supports name, required, multiple, disabled and native options.",
  ],
  [
    "toast",
    "Toast",
    "Feedback",
    "A small update, without interruption.",
    "Wrap your application once in ToastProvider. Call useToast().add({title, description}). Includes dismissal, timeouts and announcement management.",
  ],
  [
    "pagination",
    "Pagination",
    "Navigation",
    "Move through a larger collection.",
    "Controlled page, pageCount and onPageChange. Caps visible page links and disables unavailable navigation.",
  ],
  [
    "alert-dialog",
    "Alert dialog",
    "Overlays",
    "Pause before a consequential action.",
    "Uses the Coal alert-dialog role and requires explicit dismissal. Connect your handler to the confirmation button.",
  ],
  [
    "aspect-ratio",
    "Aspect ratio",
    "Data display",
    "Keep things in proportion.",
    "Use ratio (defaults to 16/9). Place responsive content inside. Invalid or negative ratios should not be supplied.",
  ],
  [
    "button",
    "Button",
    "Actions",
    "A small action. A clear intention.",
    'Use render={<a href="…" />} for links. Variants: default, secondary, outline, ghost, destructive and link. Sizes: default, sm, lg, icon.',
  ],
  [
    "button-group",
    "Button group",
    "Actions",
    "Related actions, kept together.",
    "Use aria-label to describe the group. Each button remains independently focusable.",
  ],
  [
    "toggle",
    "Toggle",
    "Actions",
    "An action with an on and off state.",
    "Use pressed/onPressedChange for controlled state and aria-label for icon-only controls.",
  ],
  [
    "input",
    "Input",
    "Inputs",
    "An understated place for a thought.",
    "Supports native input props, form validation, disabled state and React 19 refs. Always associate a label.",
  ],
  [
    "textarea",
    "Textarea",
    "Inputs",
    "A little more room to express yourself.",
    "Supports rows, minLength, maxLength, required and all native textarea props.",
  ],
  [
    "label",
    "Label",
    "Inputs",
    "A clear name for every field.",
    "Connect htmlFor to the input id. Placeholder text is not a substitute for a label.",
  ],
  [
    "field",
    "Field",
    "Inputs",
    "Label, control and feedback in one place.",
    "Coal connects labels and descriptions. Set invalid to show an error. Use FieldControl for automatic association.",
  ],
  [
    "checkbox",
    "Checkbox",
    "Inputs",
    "Choose one thing. Or a few.",
    "Compose CheckboxIndicator inside Checkbox. Supports checked, indeterminate, name, required and disabled.",
  ],
  [
    "switch",
    "Switch",
    "Inputs",
    "An immediate change, clearly expressed.",
    "Compose SwitchThumb inside Switch. Label the control. Use checked/onCheckedChange for controlled state.",
  ],
  [
    "radio-group",
    "Radio group",
    "Inputs",
    "One choice from a considered set.",
    "Provide a name and aria-label on RadioGroup. Give each RadioGroupItem a unique value and visible label.",
  ],
  [
    "select",
    "Select",
    "Inputs",
    "A familiar choice, thoughtfully styled.",
    "Compose SelectTrigger, SelectValue, SelectContent and SelectItem. Pass an items map to Select for display labels; values may be different. Coal handles selection and keyboard navigation.",
  ],
  [
    "slider",
    "Slider",
    "Inputs",
    "Find the right amount.",
    "Compose Control, Track, Indicator and Thumb. Set aria-label on SliderThumb. Supports min, max and step for one numeric value.",
  ],
  [
    "number-field",
    "Number field",
    "Inputs",
    "Precision, one step at a time.",
    "Set min, max and step on NumberField. Label the input and increment/decrement buttons.",
  ],
  [
    "card",
    "Card",
    "Data display",
    "A quiet frame for your content.",
    "Compose CardHeader, CardTitle, CardDescription, CardContent and CardFooter. Use semantic headings within CardTitle.",
  ],
  [
    "badge",
    "Badge",
    "Data display",
    "Small signals with useful meaning.",
    "Variants: default, secondary, outline, success, warning and destructive. Communicate status in text as well as color.",
  ],
  [
    "avatar",
    "Avatar",
    "Data display",
    "A person, even without a picture.",
    "Compose AvatarImage with alt text and AvatarFallback. The fallback appears when the image is unavailable.",
  ],
  [
    "table",
    "Table",
    "Data display",
    "Information that lines up.",
    "Compose TableCaption, TableHeader, TableBody, TableRow, TableHead and TableCell. Horizontal overflow stays inside its container.",
  ],
  [
    "accordion",
    "Accordion",
    "Data display",
    "A little less, until you need more.",
    "Compose Item, Header, Trigger and Content. Supports multiple expansion and arrow-key navigation.",
  ],
  [
    "collapsible",
    "Collapsible",
    "Data display",
    "Details, on your terms.",
    "Use open/onOpenChange for controlled state. Trigger and content are automatically associated.",
  ],
  [
    "separator",
    "Separator",
    "Data display",
    "Just enough separation.",
    "A semantic horizontal rule. Override className to adjust spacing.",
  ],
  [
    "scroll-area",
    "Scroll area",
    "Data display",
    "More content, within the same frame.",
    "Give the root a height. Compose Viewport and Content. Scrolling uses native scrollbars.",
  ],
  [
    "kbd",
    "Keyboard key",
    "Data display",
    "A shortcut, made visible.",
    "Use for key names in shortcut instructions. This component does not register keyboard shortcuts.",
  ],
  [
    "alert",
    "Alert",
    "Feedback",
    "Something worth your attention.",
    "Uses role=status for polite announcements. Use role=alert only for urgent errors.",
  ],
  [
    "progress",
    "Progress",
    "Feedback",
    "A clear sense of how far along.",
    "Native progress element: set value and max for a determinate value, omit value for indeterminate progress. Always label it.",
  ],
  [
    "spinner",
    "Spinner",
    "Feedback",
    "A small sign that work is happening.",
    "Includes role=status and a default Loading label. Set aria-label for more specific feedback.",
  ],
  [
    "skeleton",
    "Skeleton",
    "Feedback",
    "A familiar shape while content arrives.",
    "Set width and height to match the future content. Hidden from assistive technology. Motion respects reduced-motion preferences.",
  ],
  [
    "empty",
    "Empty state",
    "Feedback",
    "Nothing here. A useful next step.",
    "Compose a heading, explanatory text and a relevant action. Do not use an empty state for loading or errors.",
  ],
  [
    "tabs",
    "Tabs",
    "Navigation",
    "Different views, one place.",
    "Use matching values on TabsTrigger and TabsContent. Coal supports arrow keys and automatic panel association.",
  ],
  [
    "breadcrumb",
    "Breadcrumb",
    "Navigation",
    "A trail back to where you started.",
    "Compose links separated by decorative separators. Mark the current page with aria-current=page.",
  ],
  [
    "dialog",
    "Dialog",
    "Overlays",
    "A focused moment for a decision.",
    "Always include DialogTitle and DialogDescription. Escape closes, focus stays within the dialog and returns to its trigger.",
  ],
  [
    "sheet",
    "Sheet",
    "Overlays",
    "A little space beside your work.",
    "Uses the dialog primitive for focus management. Include SheetTitle, SheetDescription and an explicit action.",
  ],
  [
    "popover",
    "Popover",
    "Overlays",
    "A useful detail, close at hand.",
    "Compose PopoverTrigger and PopoverContent, plus Title and Description where appropriate. Supports controlled open state.",
  ],
  [
    "dropdown-menu",
    "Dropdown menu",
    "Overlays",
    "The right actions, within reach.",
    "Compose DropdownMenuTrigger, Content and Item. Supports keyboard navigation and disabled items.",
  ],
  [
    "hover-card",
    "Hover card",
    "Overlays",
    "A little context before you go.",
    "Supplement a link with nonessential information. Essential content must also be available at the destination.",
  ],
  [
    "tooltip",
    "Tooltip",
    "Overlays",
    "A few helpful words.",
    "Wrap the tree with TooltipProvider. Tooltips supplement an accessible name; they do not replace labels.",
  ],
];
export const catalog: CatalogItem[] = [
  ...rows.slice(8),
  ...rows.slice(0, 8),
].map(([name, title, category, description, note]) => ({
  name,
  title,
  category,
  description,
  note,
}));

const featured = [
  "button",
  "input",
  "badge",
  "card",
  "switch",
  "tabs",
  "select",
  "checkbox",
  "avatar",
];
catalog.sort(
  (a, b) =>
    (featured.includes(a.name) ? featured.indexOf(a.name) : 99) -
    (featured.includes(b.name) ? featured.indexOf(b.name) : 99),
);
